server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cto
    username: badigun
    password:
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      type: "trace"
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: false
logging.level.com.technipfmc: DEBUG


docker:
  postgres:
    enabled: false